Pi-Squared-Inc/rust-demo-semantics

- .gitignore
- Makefile
- rust-semantics/config.md
- rust-semantics/indexing.md
- rust-semantics/indexing/configuration.md
- rust-semantics/indexing/crate.md
- rust-semantics/indexing/helpers.md
- rust-semantics/indexing/initialization.md
- rust-semantics/indexing/syntax.md
- rust-semantics/indexing/trait-methods.md
- rust-semantics/indexing/trait.md
- rust-semantics/representation.md
- rust-semantics/rust.md
- tests/execution/empty.rs
The commented rules have no tests yet. I plan to add tests and uncomment them.
The indexing configuration may change and become more complex, but this is a fairly simple thing that would probably work.
> Index a trivial program

- rust-semantics/execution.md
- rust-semantics/execution/let.md
- rust-semantics/execution/statements.md
- rust-semantics/expression.md
- rust-semantics/expression/casts.md
- rust-semantics/expression/variables.md
- rust-semantics/representation.md
- rust-semantics/rust-common-syntax.md
- rust-semantics/targets/preprocessing/rust.md
- tests/execution/let-final-expression.1.run
- tests/execution/let-final-expression.rs
Closes #15 
Partly implements #16 (which still needs to work with tuples)
Partly implements #27 (constants not implemented yet)
Needs #64
> Implement: instruction sequences, let for variables, variable expressions

- Makefile
- mx-semantics/main/biguint/configuration.md
- mx-semantics/main/biguint/hooks.md
- mx-semantics/main/configuration.md
- mx-semantics/main/mx-common.md
- mx-semantics/main/syntax.md
- mx-semantics/targets/testing/configuration.md
- mx-semantics/targets/testing/mx.md
- mx-semantics/test/configuration.md
- mx-semantics/test/execution.md
- rust-semantics/targets/execution/configuration.md
- tests/mx/biguint/add.mx
- tests/mx/biguint/div.mx
- tests/mx/biguint/eq.mx
- tests/mx/biguint/gt.mx
- tests/mx/biguint/lt.mx
- tests/mx/biguint/mul.mx
- tests/mx/biguint/new.mx
- tests/mx/biguint/sub.mx
> Mx BigUint hooks

- mx-semantics/main/accounts/configuration.md
- mx-semantics/main/accounts/hooks.md
- mx-semantics/main/biguint/hooks.md
- mx-semantics/main/blocks/configuration.md
- mx-semantics/main/blocks/hooks.md
- mx-semantics/main/calls/configuration.md
- mx-semantics/main/calls/hooks.md
- mx-semantics/main/configuration.md
- mx-semantics/main/mx-common.md
- mx-semantics/main/syntax.md
- mx-semantics/test/execution.md
- tests/mx/blockchain/get-block-timestamp.mx
- tests/mx/blockchain/get-caller.mx
- tests/mx/blockchain/get-sc-balance.mx
> Mx blockchain hooks

- Makefile
- mx-semantics/main/accounts/configuration.md
- mx-semantics/main/accounts/hooks.md
- mx-semantics/main/accounts/tools.md
- mx-semantics/main/blocks/hooks.md
- mx-semantics/main/calls/configuration.md
- mx-semantics/main/calls/hooks.md
- mx-semantics/main/calls/tools.md
- mx-semantics/main/communication-mocks.md
- mx-semantics/main/configuration.md
- mx-semantics/main/mx-common.md
- mx-semantics/main/syntax.md
- mx-semantics/main/tools.md
- mx-semantics/targets/testing/mx.md
- mx-semantics/test/execution.md
- tests/mx/send/send-esdt-with-function.mx
- tests/mx/send/send-esdt.mx
Fixes #49 
This PR is more complex than usual because it tries to follow the mx-semantics repository. The main problem is that MunltiversX transfers are tightly linked with contract calls, so I also had to implement some of the call functionality.
> Send tokens

- rust-semantics/preprocessing/configuration.md
- rust-semantics/preprocessing/initialization.md
- rust-semantics/representation.md
- tests/preprocessing/storage-method.rs
> Preprocess unimplemented methods

- mx-semantics/main/accounts/code-tools.md
- mx-semantics/main/accounts/configuration.md
- mx-semantics/main/accounts/esdt-hooks.md
- mx-semantics/main/accounts/tools.md
- mx-semantics/main/biguint/tools.md
- mx-semantics/main/call-state/configuration.md
- mx-semantics/main/call-state/tools.md
- mx-semantics/main/calls/configuration.md
- mx-semantics/main/calls/hooks.md
- mx-semantics/main/calls/tools.md
- mx-semantics/main/communication-mocks.md
- mx-semantics/main/configuration.md
- mx-semantics/main/mx-common.md
- mx-semantics/main/syntax.md
- mx-semantics/test/configuration.md
- mx-semantics/test/execution.md
- tests/mx/calls/call-attached-to-transfer.mx
- tests/mx/calls/call-with-esdt.mx
- tests/mx/calls/simple-call.mx
> Contract calls

- rust-semantics/config.md
- rust-semantics/execution/calls.md
- rust-semantics/expression.md
- rust-semantics/expression/calls.md
- rust-semantics/expression/casts.md
- rust-semantics/expression/constants.md
- rust-semantics/expression/references.md
- rust-semantics/expression/tools.md
- rust-semantics/expression/variables.md
- rust-semantics/helpers.md
- rust-semantics/preprocessing/syntax.md
- rust-semantics/representation.md
- rust-semantics/rust-common-syntax.md
- rust-semantics/test/execution.md
- tests/execution/function-call.1.run
- tests/execution/function-call.2.run
- tests/execution/function-call.3.run
- tests/execution/function-call.4.run
- tests/execution/function-call.5.run
- tests/execution/function-call.7.run
- tests/execution/function-call.rs
> Rust call expressions

- Makefile
- mx-rust-semantics/main/calls/implementation.md
- mx-rust-semantics/main/glue.md
- mx-rust-semantics/main/representation.md
- mx-rust-semantics/setup/mx.md
- mx-rust-semantics/targets/contract-testing/configuration.md
- parse-mx-rust-contract-args.sh
- rust-semantics/expression.md
- rust-semantics/expression/calls.md
- rust-semantics/helpers.md
- rust-semantics/preprocessing.md
- rust-semantics/preprocessing/tools.md
- rust-semantics/representation.md
- rust-semantics/rust-common-syntax.md
- tests/mx-rust-contracts/call-endpoint-args.1.run
- tests/mx-rust-contracts/call-endpoint-args.rs
- tests/mx-rust-contracts/contract-setup-args.1.args
- tests/mx-rust-contracts/contract-setup-args.1.run
- tests/mx-rust-contracts/contract-setup-args.rs
> Allow passing args to the contract's init function

- mx-rust-semantics/targets/blockchain/mx-rust.md
- mx-rust-semantics/targets/common/configuration-testing.md
- mx-rust-semantics/targets/common/mx-rust-testing.md
- mx-rust-semantics/targets/common/mx-rust.md
- mx-rust-semantics/targets/contract-testing/configuration.md
- mx-rust-semantics/targets/contract-testing/mx-rust.md
- mx-rust-semantics/targets/testing/configuration.md
- mx-rust-semantics/targets/testing/mx-rust.md
I'm planning to add multiple testing targets for mx-rust that differ only in the initial contents of the K cell (the better way of doing this would be to run tests with a pyk-based script, but that's more work).
> Refactor kompilation targets.

- rust-semantics/error.md
- rust-semantics/expression.md
- rust-semantics/expression/assignments.md
- rust-semantics/expression/expression-list.md
- rust-semantics/expression/tuple.md
- rust-semantics/representation.md
- rust-semantics/rust-common.md
- rust-semantics/targets/preprocessing/rust.md
The implementation is incomplete, so I didn't add tests.
@ACassimiro if you approve, I'll merge. If you want to add to this PR, that's also fine.
> Tuples and assignments

- mx-rust-semantics/main/calls.md
- mx-rust-semantics/main/calls/implementation.md
- mx-rust-semantics/main/calls/macros.md
- mx-rust-semantics/main/glue.md
- mx-rust-semantics/test/execution.md
- mx-semantics/main/accounts/tools.md
- mx-semantics/main/errors/hooks.md
- mx-semantics/main/errors/tools.md
- mx-semantics/main/mx-common.md
- mx-semantics/main/syntax.md
- tests/mx-rust-contracts/require.1.run
- tests/mx-rust-contracts/require.2.run
- tests/mx-rust-contracts/require.3.run
- tests/mx-rust-contracts/require.4.run
- tests/mx-rust-contracts/require.5.run
- tests/mx-rust-contracts/require.6.run
- tests/mx-rust-contracts/require.rs
> Implement require!

- mx-rust-semantics/main/expression/rust-to-mx.md
- mx-rust-semantics/main/glue.md
- mx-rust-semantics/main/modules.md
- mx-rust-semantics/main/modules/address.md
- mx-rust-semantics/main/modules/proxy.md
- mx-rust-semantics/main/modules/send.md
- mx-rust-semantics/main/preprocessing.md
- mx-rust-semantics/main/preprocessing/contract.md
- mx-rust-semantics/main/preprocessing/methods.md
- mx-rust-semantics/main/representation.md
- tests/mx-rust-contracts/send.1.run
- tests/mx-rust-contracts/send.rs
> Implement the send() function for contracts

- mx-rust-semantics/main/expression/mx-to-rust.md
- mx-rust-semantics/main/expression/rust-to-mx.md
- mx-rust-semantics/main/glue.md
- mx-rust-semantics/main/modules.md
- mx-rust-semantics/main/modules/biguint.md
- mx-rust-semantics/main/modules/call-value.md
- mx-rust-semantics/main/preprocessing/contract.md
- mx-rust-semantics/main/representation.md
- mx-semantics/main/calls/hooks.md
- rust-semantics/error.md
- rust-semantics/expression/casts.md
- tests/mx-rust-contracts/call-value.1.run
- tests/mx-rust-contracts/call-value.rs
> Implement call_value()

- .github/workflows/build-and-test.yaml
- Makefile
- rust-semantics/config.md
- rust-semantics/full-preprocessing.md
- rust-semantics/preprocessing/syntax.md
- rust-semantics/rust-common-syntax.md
- rust-semantics/targets/preprocessing/rust.md
- ukm-semantics/main/configuration.md
- ukm-semantics/main/decoding.md
- ukm-semantics/main/decoding/syntax.md
- ukm-semantics/main/encoding.md
- ukm-semantics/main/encoding/syntax.md
- ukm-semantics/main/execution.md
- ukm-semantics/main/execution/syntax.md
- ukm-semantics/main/preprocessed-configuration.md
- ukm-semantics/main/preprocessing.md
- ukm-semantics/main/preprocessing/syntax.md
- ukm-semantics/targets/execution/configuration.md
- ukm-semantics/targets/execution/ukm-target.md
- ukm-semantics/targets/preprocessing/configuration.md
- ukm-semantics/targets/preprocessing/ukm-target.md
- ukm-semantics/targets/testing/configuration.md
- ukm-semantics/targets/testing/ukm-target.md
- ukm-semantics/test/configuration.md
- ukm-semantics/test/execution.md
> Infrastructure for the UKM semantics

- tests/ukm-contracts/erc_20_token.rs
- tests/ukm-contracts/ukm.rs
Adding the first version of the UKM-compliant ERC20 contract. The current version needs a set of features to work, as elaborated on by the TODOs in the contract:
```
TODOs:
- Integers are all u64 at the moment. Implement u256 and modify appropriately;
- Reuse the implementation of ManagedBuffer for strings, and the annotations for
the contract trait identification, as well as views, storage mappers, update, and
inits;
- Support some sort of struct for implementing MessageResult within the UKM module.
We also have to figure out the contents of MessageResult.
Observations:
- ManagedAddress was replaced by an integer to fit the behaviors of UKM;
```
These files are not associated with tests currently, and should be once the necessary infrastructure for running it is implemented.
> Adding the ERC20 contract and UKM file

- Makefile
- parsers/crates-ukm-testing-execution.sh
- parsers/test-ukm-testing-execution.sh
- rust-semantics/expression/expression-list.md
- rust-semantics/expression/tuple.md
- rust-semantics/helpers.md
- rust-semantics/representation.md
- rust-semantics/test/execution.md
- tests/ukm-contracts/bytes_hooks.rs
- tests/ukm-no-contract/test_bytes_hooks.append32.run
- tests/ukm-no-contract/test_bytes_hooks.append64.run
- tests/ukm-no-contract/test_bytes_hooks.appenddecode32.run
- tests/ukm-no-contract/test_bytes_hooks.appenddecode64.run
- tests/ukm-no-contract/test_bytes_hooks.appenddecodestr.run
- tests/ukm-no-contract/test_bytes_hooks.appendstr.run
- tests/ukm-no-contract/test_bytes_hooks.empty.run
- tests/ukm-no-contract/test_bytes_hooks.rs
- ukm-semantics/main/configuration.md
- ukm-semantics/main/execution.md
- ukm-semantics/main/hooks.md
- ukm-semantics/main/hooks/bytes.md
- ukm-semantics/targets/testing/configuration.md
- ukm-semantics/targets/testing/ukm-target.md
- ukm-semantics/test/execution.md
> Bytes hooks

- tests/ukm-with-contract/events.1.run
- tests/ukm-with-contract/events.rs
- ukm-semantics/main/preprocessing.md
- ukm-semantics/main/preprocessing/events.md
- ukm-semantics/main/preprocessing/methods.md
- ukm-semantics/main/preprocessing/syntax.md
> Empty implementation for events

- ukm-semantics/main/decoding.md
- ukm-semantics/main/decoding/impl.md
- ukm-semantics/main/encoding.md
- ukm-semantics/main/encoding/impl.md
- ukm-semantics/main/encoding/syntax.md
> Encode and decode contracts in tests

- tests/ulm-contracts/DAIMock.rs
- tests/ulm-contracts/DAIMockWBTC.rs
Merge DAIMock.rs into ulm-virgil branch.
> Ulm demo contracts - DAIMock.rs

- byol.py
- tests/ulm-contracts/DAIMock.rs
- tests/ulm-contracts/DAIMockWBTC.rs
This PR adds the name and symbol methods to the DAIMock* contracts, and updates byol.py to print the result of these calls.
Tested for DAIMock.rs (with byol), the result is
```
Name:  Dai Stablecoin
Symbol:  DAI
```
> Name and symbol added to DAIMock

- rust-semantics/rust-common-syntax.md
- tests/ulm-with-contract/erc_20_token.1.run
End of line spaces look ugly in `git diff`. Also, they sometimes generate spurious diffs (e.g. change a line, then change it back, and there may be a diff because the end of line space is no longer there).
> Remove end-of-line spaces
